apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizcardholder-deployment
  namespace: bch
  labels:
    app: bizcardholder-deployment-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bizcardholder-app
  template:
    metadata:
      labels:
        app: bizcardholder-app
    spec:
      containers:
        - name: bizcardholder
          image: localhost:5000/biz-card-holder
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bizcardholder-service
  namespace: bch
  labels:
    app: bizcardholder-service-label
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31855
  selector:
    app: bizcardholder-app
