version: '3'
services:
  api:
    build: .
    ports:
    - "65432:80"
    networks:
      - greatBE
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
    - "5432:5432"
    networks:
      - greatBE
    volumes:
    - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: leichao
      POSTGRES_PASSWORD: leichao1+1
volumes:
  postgresql:

networks:
  greatBE:
