version: '3'
services:
  api:
    build: .
    ports:
    - "80:80"
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: leichao
      POSTGRES_PASSWORD: leichao1+1
    
